version: '3'
services:
  web:
    container_name: app1_web
    image: bigby347/weblamp:1.0
    networks:
      backend:
        ipv4_address: "172.22.1.2"
    links: 
      - db:db
  admindb:
    container_name: app1_admindb
    image: phpmyadmin/phpmyadmin:latest
    networks:
      backend:
        ipv4_address: "172.22.1.3"
    ports: 
      - "8881:80"
    links: 
      - db:db
  db:
    container_name: app1_db
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3000:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: "172.22.1.250"
    env_file:
      - db_variables.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
networks: 
  backend:
    driver: bridge
    ipam: 
      config:
          - subnet: "172.22.1.0/24"
volumes:
    data: