version: '3'
services:
  web:
    container_name: dvwa_app_web
    image: vulnerables/web-dvwa
    ports: 
      - "8888:80"
    networks:
      backend:
        ipv4_address: "172.22.2.2"
networks: 
  backend:
    driver: bridge
    ipam: 
      config:
          - subnet: "172.22.2.0/24"
volumes:
    data:
